## Difference between Numpy arrays and Pytorch tensors

- GPU Usage
- AutoGrad Functionality - Automatic Gradient Computation

In [1]:
import torch

/home/ic40844/New Folder/Pytorch-Workshop/venv/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
torch.__version__

'2.4.1+cu121'

tensors -> Generalized N-dim containers of data

![Tensors](./image.png)

In [3]:
l = [1, 2, 3]
t1 = torch.tensor(l)
t1

tensor([1, 2, 3])

In [4]:
type(t1)

torch.Tensor

In [9]:
import numpy as np

In [11]:
np_array = np.array([2, 3, 4])
t2 = torch.tensor(np_array, dtype=torch.int64)
t2

tensor([2, 3, 4])

In above cell dtype must be specified, in order to create a tensor from numpy array

In [13]:
ones = torch.ones((4, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
zeros = torch.zeros((3,3,3))
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [18]:
rand = torch.rand((3,4))
rand

tensor([[0.8145, 0.8928, 0.3066, 0.9190],
        [0.8526, 0.0293, 0.3438, 0.7940],
        [0.1719, 0.7287, 0.7494, 0.2297]])

Every time we run this above cell, the outputs are differenrt, in order to make it reproducible, use `torch.manual_seed(10)`

In [40]:
torch.manual_seed(10)

rand = torch.rand((3,4))
rand

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

Random integres between 0 and 4

In [39]:
randint = torch.randint(0, 5, size=(2,2))
randint

tensor([[3, 4],
        [2, 4]])

In [41]:
arange = torch.arange(0, 10)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arange3 = torch.arange(0, 10, 3)
arange3

tensor([0, 3, 6, 9])

In [44]:
reshape = torch.arange(0, 9).reshape(3, 3)
reshape

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

If we want to create a tensor of zeros or ones, but with the shape of a different tensor

In [45]:
zeros1 = torch.zeros_like(reshape)
zeros1

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [46]:
ones1 = torch.ones_like(reshape)
ones1

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [47]:
tsr = torch.arange(0, 9).reshape(3, 3)
tsr

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## Zero dimensional Tensor

In [53]:
zerod = torch.tensor(5)
zerod

0

In [54]:
zerod = torch.tensor(3)
oned = torch.tensor([3,4,5])
twod = torch.tensor([[3,4,5], [4,6,7]])
threed = torch.tensor([[[4,5,6], [23,3,5]], [[4,5,1], [6,7,8]]])

In [59]:
print('zerod shape : ', zerod.shape)
print('oned shape : ', oned.shape)
print('twod shape : ', twod.shape)
print('threed shape : ', threed.shape)

zerod shape :  torch.Size([])
oned shape :  torch.Size([3])
twod shape :  torch.Size([2, 3])
threed shape :  torch.Size([2, 2, 3])


In [60]:
print('zerod ndim : ', zerod.ndim)
print('oned ndim : ', oned.ndim)
print('twod ndim : ', twod.ndim)
print('threed ndim : ', threed.ndim)

zerod ndim :  0
oned ndim :  1
twod ndim :  2
threed ndim :  3


## Tensor Attributes

In [48]:
tsr.shape

torch.Size([3, 3])

In [49]:
tsr.ndim

2

In [51]:
tsr.dtype

torch.int64

In [52]:
tsr.device

device(type='cpu')

By default tensors are created using `CPU`s, to use `GPU`s we need to explicitly mention the device to be `GPU`

### To check if a `GPU` is available

In [69]:
torch.cuda.is_available()

True

### To check the number of cuda devices

In [75]:
torch.cuda.device_count()

2

### To check the name of the device

In [78]:
torch.cuda.get_device_name()

'NVIDIA A100 80GB PCIe'

We can also pass the index of the device as the parameter to this function

In [79]:
torch.cuda.get_device_name(0)

'NVIDIA A100 80GB PCIe'

We can explicitly mention if we need `GPU`

In [71]:
cuda_tensor = torch.tensor([2, 4, 5], device='cuda')
cuda_tensor.device

device(type='cuda', index=0)

We can move tensors back and forth to and from `CPUs` or `GPUs`

In [73]:
cuda_tensor.to('cpu')
cuda_tensor.device

device(type='cuda', index=0)

This wouldn't work, you need to assign it to a variable

In [74]:
cuda_tensor = cuda_tensor.to('cpu')
cuda_tensor.device

device(type='cpu')

## Automatic Typecasting

In [61]:
t1 = torch.tensor([4, 6.7, 8])
t1.dtype

torch.float32

In [62]:
t1

tensor([4.0000, 6.7000, 8.0000])

Everything got upcasted

We can also explicitly set the type of the tensor

In [63]:
t2 = torch.tensor([5, 1.2, 5], dtype=torch.int64)
t2

tensor([5, 1, 5])

Everything got downcasted

## Accessing elements in a tensor

In [88]:
t = torch.tensor([[545,45,43], [54, 54, 43], [3, 56, 4]])
t[0]

tensor([545,  45,  43])

In [89]:
t[0][2]

tensor(43)

If we want to take out the scaler part laone

In [90]:
t[0][2].item()

43

Remember that only zero dimensional tensor could be taken out as a scalar

In [85]:
t[0].item()

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

#### Slicing

In [91]:
t[:1, -1]

tensor([43])

In [95]:
t[:2, 1:]

tensor([[45, 43],
        [54, 43]])

## Broadcasting

In [98]:
tensor = torch.tensor([4, 5, 5, 1, 33, 0])
tensor > 3

tensor([ True,  True,  True, False,  True, False])

In [97]:
tensor = torch.tensor([4, 5, 5, 1, 33, 0])
tensor[tensor > 3]

tensor([ 4,  5,  5, 33])

In [102]:
tensor + 10

tensor([14, 15, 15, 11, 43, 10])

## Standard Functions

In [107]:
t = t[:2]
t

tensor([[545,  45,  43],
        [ 54,  54,  43]])

In [108]:
t.sum()

tensor(784)

In [109]:
torch.sum(t)

tensor(784)

dim=0 => same shape as a row

In [111]:
t.sum(dim=0)

tensor([599,  99,  86])

dim=1 => same shape as a column

In [110]:
t.sum(dim=1)

tensor([633, 151])

In [112]:
t.max()

tensor(545)

In [113]:
t.max(dim=0)

torch.return_types.max(
values=tensor([545,  54,  43]),
indices=tensor([0, 1, 0]))

In [115]:
t.max(dim=0).values

tensor([545,  54,  43])

In [114]:
t.max(dim=0).indices

tensor([0, 1, 0])

## Matrix Multiplication

`torch.mul()`, `*` -> Element-wise multiplication

In [117]:
t1 = torch.tensor([3, 4, 5])
t2 = torch.tensor([4, 5, 6])

torch.mul(t1, t2)

tensor([12, 20, 30])

which is same as

In [118]:
t1 * t2

tensor([12, 20, 30])

`torch.mul()`, `@` -> Matrix multiplication

In [119]:
t3 = torch.tensor([[3, 4, 5], [4, 6, 1]])
t4 = torch.tensor([[4, 5], [5, 1], [9, 8]])

torch.matmul(t3, t4)

tensor([[77, 59],
        [55, 34]])

which is same as

In [120]:
t3 @ t4

tensor([[77, 59],
        [55, 34]])

## Computing gradients

To compute gradients, the `dtype` must be of float type

In [64]:
grad = torch.tensor([5, 6, 7], requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [66]:
grad = torch.tensor([5, 6, 7], dtype=torch.float32, requires_grad=True)
grad

tensor([5., 6., 7.], requires_grad=True)