## Difference between Numpy arrays and Pytorch tensors

- GPU Usage
- AutoGrad Functionality - Automatic Gradient Computation

In [1]:
import torch

In [2]:
torch.__version__

'2.4.1+cu121'

tensors -> Generalized N-dim containers of data

![Tensors](./image.png)

In [3]:
l = [1, 2, 3]
t1 = torch.tensor(l)
t1

tensor([1, 2, 3])

In [4]:
type(t1)

torch.Tensor

In [5]:
import numpy as np

In [6]:
np_array = np.array([2, 3, 4])
t2 = torch.tensor(np_array, dtype=torch.int64)
t2

tensor([2, 3, 4])

In above cell dtype must be specified, in order to create a tensor from numpy array

In [7]:
ones = torch.ones((4, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
zeros = torch.zeros((3,3,3))
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [9]:
rand = torch.rand((3,4))
rand

tensor([[0.6718, 0.0362, 0.6799, 0.7120],
        [0.9763, 0.3413, 0.4782, 0.1874],
        [0.4241, 0.6345, 0.7422, 0.4066]])

Every time we run this above cell, the outputs are differenrt, in order to make it reproducible, use `torch.manual_seed(10)`

In [10]:
torch.manual_seed(10)

rand = torch.rand((3,4))
rand

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

Random integres between 0 and 4

In [11]:
randint = torch.randint(0, 5, size=(2,2))
randint

tensor([[1, 0],
        [1, 3]])

In [12]:
arange = torch.arange(0, 10)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arange3 = torch.arange(0, 10, 3)
arange3

tensor([0, 3, 6, 9])

In [14]:
reshape = torch.arange(0, 9).reshape(3, 3)
reshape

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

If we want to create a tensor of zeros or ones, but with the shape of a different tensor

In [15]:
zeros1 = torch.zeros_like(reshape)
zeros1

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [16]:
ones1 = torch.ones_like(reshape)
ones1

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [17]:
tsr = torch.arange(0, 9).reshape(3, 3)
tsr

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## Zero dimensional Tensor

In [18]:
zerod = torch.tensor(5)
zerod

tensor(5)

In [19]:
zerod = torch.tensor(3)
oned = torch.tensor([3,4,5])
twod = torch.tensor([[3,4,5], [4,6,7]])
threed = torch.tensor([[[4,5,6], [23,3,5]], [[4,5,1], [6,7,8]]])

In [20]:
print('zerod shape : ', zerod.shape)
print('oned shape : ', oned.shape)
print('twod shape : ', twod.shape)
print('threed shape : ', threed.shape)

zerod shape :  torch.Size([])
oned shape :  torch.Size([3])
twod shape :  torch.Size([2, 3])
threed shape :  torch.Size([2, 2, 3])


In [21]:
print('zerod ndim : ', zerod.ndim)
print('oned ndim : ', oned.ndim)
print('twod ndim : ', twod.ndim)
print('threed ndim : ', threed.ndim)

zerod ndim :  0
oned ndim :  1
twod ndim :  2
threed ndim :  3


## Tensor Attributes

In [22]:
tsr.shape

torch.Size([3, 3])

In [23]:
tsr.ndim

2

In [24]:
tsr.dtype

torch.int64

In [25]:
tsr.device

device(type='cpu')

By default tensors are created using `CPU`s, to use `GPU`s we need to explicitly mention the device to be `GPU`

### To check if a `GPU` is available

In [26]:
torch.cuda.is_available()

True

### To check the number of cuda devices

In [27]:
torch.cuda.device_count()

2

### To check the name of the device

In [28]:
torch.cuda.get_device_name()

'NVIDIA A100 80GB PCIe'

We can also pass the index of the device as the parameter to this function

In [29]:
torch.cuda.get_device_name(0)

'NVIDIA A100 80GB PCIe'

We can explicitly mention if we need `GPU`

In [30]:
cuda_tensor = torch.tensor([2, 4, 5], device='cuda')
cuda_tensor.device

device(type='cuda', index=0)

We can move tensors back and forth to and from `CPUs` or `GPUs`

In [31]:
cuda_tensor.to('cpu')
cuda_tensor.device

device(type='cuda', index=0)

This wouldn't work, you need to assign it to a variable

In [32]:
cuda_tensor = cuda_tensor.to('cpu')
cuda_tensor.device

device(type='cpu')

## Automatic Typecasting

In [33]:
t1 = torch.tensor([4, 6.7, 8])
t1.dtype

torch.float32

In [34]:
t1

tensor([4.0000, 6.7000, 8.0000])

Everything got upcasted

We can also explicitly set the type of the tensor

In [35]:
t2 = torch.tensor([5, 1.2, 5], dtype=torch.int64)
t2

tensor([5, 1, 5])

Everything got downcasted

## Accessing elements in a tensor

In [36]:
t = torch.tensor([[545,45,43], [54, 54, 43], [3, 56, 4]])
t[0]

tensor([545,  45,  43])

In [37]:
t[0][2]

tensor(43)

If we want to take out the scaler part laone

In [38]:
t[0][2].item()

43

Remember that only zero dimensional tensor could be taken out as a scalar

In [39]:
t[0].item()

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

#### Slicing

In [40]:
t[:1, -1]

tensor([43])

In [41]:
t[:2, 1:]

tensor([[45, 43],
        [54, 43]])

## Broadcasting

In [42]:
tensor = torch.tensor([4, 5, 5, 1, 33, 0])
tensor > 3

tensor([ True,  True,  True, False,  True, False])

In [43]:
tensor = torch.tensor([4, 5, 5, 1, 33, 0])
tensor[tensor > 3]

tensor([ 4,  5,  5, 33])

In [44]:
tensor + 10

tensor([14, 15, 15, 11, 43, 10])

## Standard Functions

In [45]:
t = t[:2]
t

tensor([[545,  45,  43],
        [ 54,  54,  43]])

In [46]:
t.sum()

tensor(784)

In [47]:
torch.sum(t)

tensor(784)

dim=0 => same shape as a row

In [48]:
t.sum(dim=0)

tensor([599,  99,  86])

dim=1 => same shape as a column

In [49]:
t.sum(dim=1)

tensor([633, 151])

In [50]:
t.max()

tensor(545)

In [51]:
t.max(dim=0)

torch.return_types.max(
values=tensor([545,  54,  43]),
indices=tensor([0, 1, 0]))

In [52]:
t.max(dim=0).values

tensor([545,  54,  43])

In [53]:
t.max(dim=0).indices

tensor([0, 1, 0])

## Matrix Multiplication

`torch.mul()`, `*` -> Element-wise multiplication

In [54]:
t1 = torch.tensor([3, 4, 5])
t2 = torch.tensor([4, 5, 6])

torch.mul(t1, t2)

tensor([12, 20, 30])

which is same as

In [55]:
t1 * t2

tensor([12, 20, 30])

`torch.mul()`, `@` -> Matrix multiplication

In [56]:
t3 = torch.tensor([[3, 4, 5], [4, 6, 1]])
t4 = torch.tensor([[4, 5], [5, 1], [9, 8]])

torch.matmul(t3, t4)

tensor([[77, 59],
        [55, 34]])

which is same as

In [57]:
t3 @ t4

tensor([[77, 59],
        [55, 34]])

### Transpose

In [58]:
t3.T

tensor([[3, 4],
        [4, 6],
        [5, 1]])

## Storing and loading tensors/models

In [60]:
torch.save(t3, 'weights.pt')

some people may also use `.pth` as an extension

`torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling

In [64]:
t3 = torch.load('weights.pt', weights_only=True)
t3

tensor([[3, 4, 5],
        [4, 6, 1]])

In [44]:
a = torch.tensor([[1.00001, 2.00002], [3.00004, 4.00001]])
b = torch.tensor([[1., 2], [3, 4]])

torch.allclose(a, b, atol=1e-4)

True

In [45]:
torch.allclose(a, b, atol=1e-5)

False

In [43]:
vec = torch.linspace(-5, 5, 10)
vec

tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])

In [42]:
vec2 = torch.clone(vec)
vec2

tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])

## Computing gradients

To compute gradients, the `dtype` must be of float type

In [58]:
grad = torch.tensor([5, 6, 7], requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [66]:
grad = torch.tensor([5, 6, 7], dtype=torch.float32, requires_grad=True)
grad

tensor([5., 6., 7.], requires_grad=True)

## AutoGrad

Note that
- `requires_grad` must be set to `True`, to compute gradient
- `grad` is an attribute,`backward()` is a function
- Perform `backward()` for the function y
- `dy/dx` can be found by `x.grad`

In [46]:
x = torch.tensor(12., requires_grad=True)
y = 3*x**2
y.backward()
x.grad

tensor(72.)

We can also do this for functions having more than one variable

In [49]:
x = torch.tensor(12., requires_grad=True)
z = torch.tensor(3., requires_grad=True)
y = 3*x**2 - z**3
y.backward()
print('dy/dx =',x.grad)
print('dy/dz =',z.grad)

dy/dx = tensor(72.)
dy/dz = tensor(-27.)


In this case, if atleast only one variable has `requires_grad=True`, we won't encounter an error

In [50]:
x = torch.tensor(12., requires_grad=True)
z = torch.tensor(3., requires_grad=False) # requires_grad has been set to False
y = 3*x**2 - z**3
y.backward()
print('dy/dx =',x.grad)
print('dy/dz =',z.grad)

dy/dx = tensor(72.)
dy/dz = None
